# Generated by Django 2.1.3 on 2018-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('topic', models.CharField(max_length=50)),
                ('lecture_no', models.CharField(max_length=50)),
            ],
        ),
    ]
