# Generated by Django 2.1.3 on 2018-11-19 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
