# Generated by Django 2.1.3 on 2018-11-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20181119_2032'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.Syllabus'),
        ),
    ]
